### PR TITLE
refactor(overlay-kit): apply immer

### PR DESCRIPTION
**Pull request by po4tion**
I changed the code that was marked with "spread operator" to make it readable.

"Immer" improves not only readability but also maintenance. However, if immer is added to the overlay-kit that claims "Small Bundle Size", I am concerned about increasing the size.

### CODE REVIEW

**Comment by jungpaeng** [comment]
I completely agree that using immer can lead to more readable code without the need for spread operators. This is likely why many libraries that deal with objects have integrated immer.

However, as you mentioned, there is a possibility of an increased bundle size and the additional burden of a new dependency, which currently doesn’t exist.

@manudeli What are your thoughts on this?

**Comment by manudeli** [comment]
Thanks for the great idea. However, I still don't understand whether it is absolutely necessary to add another dependency, immer. When using immer, we should be forced to understand the concepts of immer, so I think it is better not to add it.

> "Immer" improves not only readability but also maintenance. However, if immer is added to the overlay-kit that claims "Small Bundle Size", I am concerned about increasing the size.

You mentioned about improving **readability** and **maintenance**. but I think that's something we can think of differently depending on perspective.

1. **Readability**: It would be better if improving readability did not require understanding the concept of immer.

2. **Maintenance**: Having no dependencies is a good thing in terms of library stability. For example, there is no need to care immer errors or BREAKING CHANGE.

and

3. **Marketing Point**: Zero Dependency can be a good marketing point to promote our library

Therefore, In my opinion I hope that this Pull Request is not accepted.

**Comment by po4tion** [comment]
@jungpaeng @manudeli 

I look at your opinion positively in that you need to understand the concept of "immer".

This is an increase in human cost and even if "immer" is applied at the same time, it will be difficult to expect more effects than expected.

Also, I think it's a bad thing to break the project's rejection of new dependencies, which is the concern I've had. So I think it's better to close this PR.

Thank you for giving me a good opinion.

**Comment by manudeli** [comment]
> @jungpaeng @manudeli
> 
> I look at your opinion positively in that you need to understand the concept of "immer".
> 
> This is an increase in human cost and even if "immer" is applied at the same time, it will be difficult to expect more effects than expected.
> 
> Also, I think it's a bad thing to break the project's rejection of new dependencies, which is the concern I've had. So I think it's better to close this PR.
> 
> Thank you for giving me a good opinion.

I love your good try and thanks for accepting my opinion! 🙇

**Pull request closed without merging**
